In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

#### 1. Iris Dataset for Multiclass Classification

In [2]:

data = load_iris( as_frame=True)

In [3]:
data

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 'target': 0     

In [4]:
X=data.data.values

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
Y=data.target

In [7]:
target=pd.get_dummies(Y).values

In [8]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [9]:
target

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

#### 2. Split the train and test set

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X, target, test_size = 0.3, random_state = 42)

In [11]:
len(x_train)

105

#### 3. The Implementation of Multiclass Classification in Python

In [12]:
class  multi_class_classifier():

    """
    write a class named multi_class_classifier using object oriented programming in Python with attributes and methods.

    """

    def __init__(self, layer_neurons = [4, 4, 3], activations=['relu', 'softmax']):
        """
        layer_neurons: the vector where the first element denotes the number of neurons in the input layer, 
                       the last element denotes the number of neurons in the output layers.
        activations: the vector of activation function used in the neural network.
        
        """


        assert(len(layer_neurons) == len(activations)+1)
        self.layer_neurons = layer_neurons
        self.activations = activations
        self.weights = []
        self.biases = []
        #self.batchsize=batchsize
        for i in range(len(layer_neurons)-1):
            self.weights.append(np.random.randn(layer_neurons[i+1], layer_neurons[i]))
            self.biases.append(np.random.randn(layer_neurons[i+1], 1))

    def getActivationFunction(self,name):
        """
        define the vector based activation functions
        
        """
        if(name == 'sigmoid'):
            return lambda x : np.exp(x)/(1+np.exp(x))

        elif(name == 'linear'):
            return lambda x : x

        elif(name == 'relu'):
            def relu(x):
                y = np.copy(x)
                y[y<0] = 0
                return y
            return relu

        elif(name == 'softmax'):
            return lambda x : np.exp(x) / np.sum(np.exp(x))

        else:
            print('Unknown activation function. linear is used')
            return lambda x: x


    def crossentropy(self,y,y_pred):
        """
        the cost function for the multinomial classification problem:
            y is the grund truth for the target feature vector,
            y_pre is the predicted target featurs vector from the neural network

        """
        return -np.dot(y,np.log(y_pred))


    def feedforward(self, x):
        """
        Implementating feedforward algorithm, namely calculating wX + b, and activating it through all layers.

        """
        a = np.copy(x)
        z_s = []
        a_s = [a]
        for i in range(len(self.weights)):
            activation_function = self.getActivationFunction(self.activations[i])
            z_s.append(self.weights[i].dot(a) + self.biases[i])
            a = activation_function(z_s[-1])
            a_s.append(a)

        return (z_s, a_s)


    def backpropagation(self,y, z_s, a_s):

        """
        Implementing backpropagation and derive the gradients with respect to weights and biases.

        """
        dw = []  # dC/dW
        db = []  # dC/dB
        deltas = [None] * len(self.weights)  # delta = dC/dZ  is known as error for each layer

        # calculate the error dC/dZ for output layer (activation function is softmax)
        temp=self.getActivationFunction(self.activations[-1])(z_s[-1])
        output_net=np.concatenate((temp.T, temp.T ,temp.T), axis=0).T-np.identity(3)
        deltas[-1] =  output_net.dot(y)


        # implementing BackPropagation
        for i in reversed(range(len(deltas)-1)):

            deltas[i] = (self.weights[i+1].T.dot(deltas[i+1]))*(self.getDerivitiveActivationFunction(self.activations[i])(z_s[i]))  
            dw = [d.dot(a_s[i].T) for i,d in enumerate(deltas)]
            db = [d for d in deltas]
            return dw,db

    def getDerivitiveActivationFunction(self, name):
        """
        derive the vector based gradients of the activation functions 

        """
        if(name == 'sigmoid'):
            sig = lambda x : np.exp(x)/(1+np.exp(x))
            return lambda x :sig(x)*(1-sig(x)) 
        elif(name == 'linear'):
            return lambda x: 1
        elif(name == 'relu'):
            def relu_diff(x):
                y = np.copy(x)
                y[y>=0] = 1
                y[y<0] = 0
                return y
            return relu_diff
        else:
            print('Unknown activation function. linear is used')
            return lambda x: 1
    

    def train(self, X, target, epochs=1500, lr = 0.008):
      """ 
      train the neural network using the training dataset and update weights and biases
      lr: the learning rate with default value setting to 0.00005
      X: input feature vector
      target: the target feature vector (after implementing one-hot encoding)
      epochs: the number of times of training (feedforward and backward propagation) to run through all data points in the training dataset.

      """
      for e in range(epochs): 
          i=0
          training_loss=0
          dw_total=[np.zeros((4,4)),np.zeros((3,4))]
          db_total=[np.zeros((4,1)),np.zeros((3,1))]
          while i<len(X):
                x_batch = X[i:i+1].reshape(4,1)
                y_batch = target[i:i+1].reshape(3,1)
                z_s, a_s = self.feedforward(x_batch)
                dw, db = self.backpropagation(y_batch, z_s, a_s)
                dw_total=[i+j for i,j in zip(dw_total,dw)]
                db_total=[i+j for i,j in zip(db_total,db)]

                y=y_batch.reshape(3,)
                y_pred=a_s[-1].reshape(3,)
    
                training_loss+=self.crossentropy(y,y_pred)
                i+=1
          
          # calculate the average of the gradients across all data points within one epoch
          dw_total=[i/len(X) for i in dw_total]
          db_total=[i/len(X) for i in db_total]

          # update the weights using gradient descent using average gradients with one epoch 

          self.weights = [w-lr*dweight for w,dweight in  zip(self.weights, dw_total)]
          self.biases = [w-lr*dbias for w,dbias in  zip(self.biases, db_total)]

          training_loss=training_loss/len(X)
          print("Epoch = {} ---------------------".format(e+1)+"Training loss = {}".format(self.crossentropy(y,y_pred)))

    def predict(self,x):
        prediction = np.array([[0,0,0]])
        i=0
        while i<len(x):
            x_batch = x[i:i+1].reshape(4,1)
            z,a = self.feedforward(x_batch)
            y_batch=a[-1].reshape(1,3)
            prediction = np.concatenate((prediction, y_batch),axis=0)
            #prediction=prediction[1:]
            i+=1
        return prediction[1:]
        

    



#### 4. Use the self-Written Class multi_class_classifier to train and evaluate the neural network

In [13]:
classifier= multi_class_classifier()


##### 4.1 Train the Model 

In [14]:
classifier.train(x_train,y_train)

Epoch = 1 ---------------------Training loss = 26.908109379181123
Epoch = 2 ---------------------Training loss = 23.67066255396274
Epoch = 3 ---------------------Training loss = 20.74463200997558
Epoch = 4 ---------------------Training loss = 18.097528957256728
Epoch = 5 ---------------------Training loss = 15.69999163635256
Epoch = 6 ---------------------Training loss = 13.525588906561463
Epoch = 7 ---------------------Training loss = 11.550837095822024
Epoch = 8 ---------------------Training loss = 9.755631236725083
Epoch = 9 ---------------------Training loss = 8.124420327105755
Epoch = 10 ---------------------Training loss = 6.648500036109381
Epoch = 11 ---------------------Training loss = 5.329322240002885
Epoch = 12 ---------------------Training loss = 4.1809815630534715
Epoch = 13 ---------------------Training loss = 3.2274171483073943
Epoch = 14 ---------------------Training loss = 2.4897106367226978
Epoch = 15 ---------------------Training loss = 1.9659976521813765
Epoch = 16 

##### 4.2 Evaluate the Model

In [15]:
predict_prob=classifier.predict(x_test)

In [16]:
predict_class=np.argmax(predict_prob,axis=1)

In [17]:
predict_class

array([2, 0, 2, 1, 2, 0, 1, 1, 2, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [18]:
true_class=np.argmax(y_test,axis=1)

In [19]:
accuracy_ratio=np.sum(predict_class==true_class)/len(true_class)

In [20]:
accuracy_ratio

0.8666666666666667